export const UsuariosImpl = [
    {
        id: 1,
        nome: 'Jorge Souza',
        instituicao: 'UERJ',
        unidade: 'UERJ-ZO',
        cep: '23071160',
        curso: 'TADS',
        modelo: 'Presencial',
        estrelas:200,
    },
    {
        id: 2,
        nome: 'Aline Fernandes',
        instituicao: 'UERJ',
        unidade: 'UERJ-ZO',
        cep: '23071160',
        curso: 'Farmácia',
        modelo: 'Presencial',
        estrelas:120,
    },
    {
        id: 3,
        nome: 'Emanoel Rosa',
        instituicao: 'UERJ',
        unidade: 'UERJ-ZO',
        cep: '23071160',
        curso: 'Ciência da Computação',
        modelo: 'Presencial',
        estrelas:200,
    },
    {
        id: 4,
        nome: 'Vera Silva',
        instituicao: 'UERJ',
        unidade: 'UERJ-ZO',
        cep: '23071160',
        curso: 'TADS',
        modelo: 'Presencial',
        estrelas:205,
    },
];
