DROP PROCEDURE IF EXISTS insert_area;
DROP FUNCTION IF EXISTS idArea;
DROP FUNCTION IF EXISTS idTema;
DROP FUNCTION IF EXISTS idQuestao;
DROP FUNCTION IF EXISTS idTemaQuestao;
DROP FUNCTION IF EXISTS idOpcao;
DROP FUNCTION IF EXISTS idArtigo;